import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tymur Bondar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        {/* Layout UI */}
        <Navbar />
        <main className="h-screen bg-base-100">{children}</main>
      </body>
    </html>
  )
}